### ISSUE TITLE
Trailing semicolon is required

### ISSUE THREAD

**Issue by andy1547** [jasonmcboyd/ASI_cEnvironment#1]
A trailing semicolon is required for the last path entry otherwise windows will not pick it up.

Currently the resource assumes there's no trailing semicolon causing Convert-Path to fail due to an empty string in the last $path array element.

Additionally when adding/subtracting from the path, the trailing semicolon is not added or removed if it previously existed.

A simple fix is to remove the empty element and to concatenate a trailing semicolon.
Will submit a PR.

**Comment by andy1547** [comment]
See PR https://github.com/jasonmcboyd/ASI_cEnvironment/pull/2
This still doesn't solve a potential issue where the path entries are correct but there's no trailing semicolon, yet the test resource would report its correct.
This could potentially be changed so the test resource reports $false in this case and fixes the ; (despite to changes to path entries).

**Comment by jasonmcboyd** [comment]
Hi Andy,
I have never heard of the path requiring a trailing semicolon before. My path variable does not have a trailing semicolon and the last path appears to function fine. A quick Google search did not turn up anything to support that either. I think handling the case where a path variable does have a trailing semicolon (leading to an empty string in the array) is a good idea though.

**Comment by andy1547** [comment]
Hi Jason,
You are correct, no trailing semicolon is required for the last path variable to work. 

However adding a trailing semicolon is required to not break the new Windows UI for editing path variables (see https://betanews.com/wp-content/uploads/2015/11/Path.jpg).
This new UI gives the ability to easily add/edit/remove individual values of the path, however on doing so it adds a trailing semicolon.

Moreover, not having a trailing slash causes two glitches in this new UI:
- If there is only one value added to the path but no trailing semicolon, the fancy new individual value UI does not appear, instead the old dialog for editing the entire path string is shown. Once you add atrailing semicolon the new UI is shown correctly.
-  If more than one value is added to the path but no trailing semicolon, the new UI is displayed but if you try to edit the entire path string, a warning confirmation box is shown saying "This will discard any changes made in this dialog and edit this value as text instead". If a semicolon is added you have the ability to switch between the new UI and old (entire path string) editing methods freely.

Finally, when there are no values in the path the new Windows UI expects an empty string.

**Comment by jasonmcboyd** [comment]
Your pull request has been merged. Thanks!
